name: r2z Thunderbird Win32

on:
  schedule:
  - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setup Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: pip install -r r2z-mzla-requirements.txt

      - name: r2z-Pre
        run: python r2ztb-win32.py

      - name: Check Vars
        if: env.DIFF != 'None'
        run: |
             echo ${{ env.CHANNEL }}
             echo ${{ env.PKGNAME }}
             echo ${{ env.TBVERSION }}
             echo ${{ env.TBZIPFILE }}

      - name: Unzip Executable
        if: env.DIFF != 'None'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ env.PKGNAME }}
          pathTarget: "TbTemp32"

      - name: Move Core Directory
        if: env.DIFF != 'None'
        run: mv './TbTemp32/core' './core32'

      - name: Make Portable
        if: env.DIFF != 'None'
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 ${{ env.TBZIPFILE }} ./core32/*

      - name: Release
        if: env.DIFF != 'None'
        uses: xresloader/upload-to-github-release@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ env.TBZIPFILE }}"
          draft: false
          tag_name: 'tb-win32'

      - name: Commit update file
        if: env.DIFF != 'None'      
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Thunderbird Win32 ${{ env.TBVERSION }}
          push_options: '--force'
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          file_pattern: updates/r2ztb
