name: r2z Thunderbird Nightly Win64

on:
  schedule:
  - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: pip install -r r2z-mzla-requirements.txt

      - name: r2z-Pre
        run: python r2ztb-nightly-win64.py

      - name: Check Vars
        if: env.DIFF != 'None'
        run: |
             echo ${{ env.CHANNEL }}
             echo ${{ env.PKGNAME }}
             echo ${{ env.TBVERSION }}
             echo ${{ env.TBZIPFILE }}

      - name: Unzip Executable
        if: env.DIFF != 'None'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ env.PKGNAME }}
          pathTarget: "TbTemp64"

      - name: Move Core Directory
        if: env.DIFF != 'None'
        run: mv './TbTemp64/core' './core64'

      - name: Make Portable
        if: env.DIFF != 'None'
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 ${{ env.TBZIPFILE }} ./core64/*

      - name: Release
        if: env.DIFF != 'None'
        uses: xresloader/upload-to-github-release@v1.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ env.TBZIPFILE }}"
          draft: false
          tag_name: 'tb-nightly-win64'
          update_latest_release: true

      - name: Commit update file
        if: env.DIFF != 'None'      
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Thunderbird Nightly Win64 ${{ env.TBVERSION }}
          push_options: '--force'
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          file_pattern: updates/r2ztb-nightly-64

